### PR TITLE
Start smartbanner with SmartBanner() function

### PR DESCRIPTION
**Pull request by matass**
Lets add some control

### CODE REVIEW

**Comment by MatasSim** [comment]
we have rails application which stores 3 shops. What if we don't want to show banner in one of them? the best way to handle this problem is to call a function which starts smartbanner. If the page doesn't have meta tags - we're getting error: `Error: No options detected. Please consult documentation.` 
example: 
```html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="smartbanner:title" content="Smart Application">
  <meta name="smartbanner:author" content="SmartBanner Contributors">
  <meta name="smartbanner:price" content="FREE">
  <meta name="smartbanner:price-suffix-apple" content=" - On the App Store">
  <meta name="smartbanner:price-suffix-google" content=" - In Google Play">
  <meta name="smartbanner:icon-apple" content="http://a3.mzstatic.com/us/r30/Purple60/v4/c1/3b/b0/c13bb085-64c0-cc90-f97a-521b96963986/icon350x350.jpeg">
  <meta name="smartbanner:icon-google" content="http://lh3.ggpht.com/f4oX61ljZ6x8aYDELZOgxlvdUEu73-wSQ4fy5bx6fCRISnZP8T353wdaM43RO_DbGg=w300">
  <meta name="smartbanner:button" content="View">
  <meta name="smartbanner:button-url-apple" content="https://itunes.apple.com/us/genre/ios/id36?mt=8">
  <meta name="smartbanner:button-url-google" content="https://play.google.com/store">
  <meta name="smartbanner:enabled-platforms" content="android,ios"> -->
  <!-- Enable for all platforms -->
  <!-- <meta name="smartbanner:include-user-agent-regex" content=".*"> -->
  <link rel="stylesheet" href="smartbanner.css">
  <script src="smartbanner.js"></script>
</head>
<body>
  <h1>&nbsp;</h1>
  <script>
    var onLoadHandlerForConflictTesting = function() {};
    window.onload = onLoadHandlerForConflictTesting;
  </script>
</body>
</html>
```

**Comment by MatasSim** [comment]
I think it's not a good practice to start scripts automagically especially when we get some error messages. So if I understand correctly this script must work automagically and no mater what changes I'd make to add some initialization functionality?

**Comment by ain** [comment]
Yes, the goal of `smartbanner.js` is to mimic built-in _Apple's Smart App Banner_ behaviour, but with customisations based on more metadata. The goal is to retain full usability at 0 JavaScript.

I think even in your case it'd be possible to avoid the missing options error with just one meta tag:

  ```html
  <meta name="smartbanner:enabled-platforms" content="none">
  ```

Alternatively we could discuss failing silently and removing the error thrown. @fkoester, since you're one of the active contributors, any ideas?

**Comment by fkoester** [comment]
@ain I would also prefer to keep the current "automagic" behavior, I think it is quite elegant.

@MatasSim If you have some pages that should not show the smartbanner and do not include any meta-tags for it, why not just exclude the `smartbanner.js` script from those pages as well? Then no code is run automagically an no errors are thrown.

**Comment by MatasSim** [comment]
@fkoester we can't exclude `smartbanner.js` from the assets pipeline. I will try to add this meta tag to template: `<meta name="smartbanner:enabled-platforms" content="none">`. Thank you both for replies.

**Comment by ain** [comment]
@matass I'm closing your PR in respect to above discussion. Sorry for not being able to address your concerns directly.

**Comment by matass** [comment]
that's ok

**Pull request closed without merging**
