### PR TITLE
Allow to enable/disable smart banner for certain UAs

### PR DESCRIPTION
**Pull request by fkoester**
A new option "exclude-user-agent-regex" is added, which allows to define
a regular expression for User Agent strings for which the smart app
banner should not be shown.

### CODE REVIEW

**Comment by ain** [comment]
Good work! I like the idea. 

You did consider the `platformEnabled` directive, right? 

I'd imagine that support for a device is calculated in a decision chain of 

1. Do we have platform enabled?
2. Do we have UA enabled?

I hope you considered it in this fashion? Otherwise we may have feature collisions.

**Comment by fkoester** [comment]
> Good work! I like the idea.

Thanks!

> You did consider the platformEnabled directive, right?
>
> I'd imagine that support for a device is calculated in a decision chain of
>
> *  Do we have platform enabled?
> *  Do we have UA enabled?
>
> I hope you considered it in this fashion? Otherwise we may have feature collisions.

That is exactly how it is implemented, as you can see in `smartbanner.js`:

```javascript
publish() {
  [...]
  else if (Bakery.baked || !Detector.platform() || !this.platformEnabled || this.userAgentExcluded) {
    return false;
  }
  [...]
}
```

The smart banner is not published if (in this order):
* No mobile platform detected: `!Detector.platform()`
* Platform is disabled: `!this.platformEnabled`
* User Agent is explicitly excluded using the new regex option: `this.userAgentExcluded`

**Comment by fkoester** [comment]
I forgot to mention in the intended use cases for this functionality, but maybe you already saw the README changes or figured yourself.

But for the sake of completeness:

There are cases where you do not want to show the smart app banner on all Android and/or all iOS devices. For example:
* your app is availabe only for some Android/iOS versions
* your app is only availabe on iPhone, but not iPad
* your app is a web app which also shows this website, but of course should not show the smart app banner.

In this case you can define a regular expression, which matches all user agent strings that should be excluded. Just add another `meta` tag like the following:
```
<meta name="smartbanner:exclude-user-agent-regex" content="^.*My Example Webapp$">
```
This regular expression would match any user agent string, that ends with *My Example Webapp*.

**Further thoughts:**
The PR does not implement this, but maybe also the opposite logic might be useful for some people. Instead of defining a "blacklist" of user agent strings, one could also define a "whitelist", ideally again by a regular expression.

Supposing the whitelist match is called `userAgentIncluded`), the logic could be:

```javascript
const showSmartBanner = (this.platformEnabled || this.userAgentIncluded) && !this.userAgentExcluded;
```

This way you could for example enable all Android devices via `enabled-platforms="android"` and some iOS devices only by `include-user-agent-regex="iPhone 7.*"`

**Comment by ain** [comment]
Yeah, I saw, very nicely prepped PR. I'll run a few tests (never hurts) and go through the code in detail. 

Good thing is we have legacy support here, so no major release needed.

**Comment by fkoester** [comment]
I now updated the PR to also contain a `include-user-agent-regex`option. I did not test it yet, though.

**Comment by fkoester** [comment]
I updated and rebased the PR again. It includes now more unit tests.

**Comment by ain** [comment]
I finally found time for testing your feature manually as well. Thanks a lot for a great addition @fkoester!

**Pull request merged**
